apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: {namespace_name}
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: base-application-
    patch: |-
      - op: replace
        path: /spec/source/repoURL
        value: https://github.com/volvo-cars/openshift-charts
      - op: replace
        path: /spec/project
        value: base-application-project
      - op: replace
        path: /spec/source/chart
        value: onboard-team
      - op: replace
        path: /spec/source/targetRevision
        value: 1.0.2
      - op: replace
        path: /spec/source/helm/values
        value: |
          namespace:
            name: {namespace_name}
          quota:
            enabled: true
            hard:
              requests.cpu: "20"
              requests.memory: 80Gi
              limits.cpu: "40"
              limits.memory: 160Gi
          psa:
            level: restricted
            mode: enforce    
          rbac:
            OIDCGroupMapping:
              "{aad_group}": "namespace-admin"
          argocdproperties:
            projectconfig:
              enabled: true
              groups:
               "{aad_group_id}": "argoapp-admin"
            allowedSourceRepos:
              - "{app_repo}"
          extraLabels:
            "AppID": "{app_id}" 
            "istio.io/rev": "default"
            "istio-injection": "disabled"
            "component": "application"

