resources:
  - ../base
  - ocp-sandbox-net-cm.yaml
  - onboard-sandbox-net.yaml
  - namespace-sandbox-net.yaml
  - namespace-sandbox-iod.yaml
  - mfg-rbac-kustomization.yaml
#  - ../../cluster_config/sandbox-net/
#  - ../../cluster_config/iod-sandbox/
