apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mfg-rbac-kustomization
  namespace: flux-system
spec:
  interval: 5m
  path: "./config/mfg_rbac"
  sourceRef:
    kind: GitRepository
    name: git-repo-openshift-onboard
  prune: true
  #postBuild:
  #  substituteFrom:
  #    - kind: ConfigMap
  #      name: ocp-sandbox-net-cm
  #      optional: true
