apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onboard-sandbox-net
  namespace: flux-system
spec:
  interval: 5m
  path: "./namespace/sandbox-net"
  sourceRef:
    kind: GitRepository
    name: git-repo-openshift-gitops
  prune: true
  #postBuild:
  #  substituteFrom:
  #    - kind: ConfigMap
  #      name: ocp-sandbox-net-cm
  #      optional: true
