apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mfg-access-sandbox-release
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./.charts/ocp-onboard
      sourceRef:
        kind: GitRepository
        name: git-repo-openshift-gitops
        namespace: flux-system 
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: mfg-access-sandbox-values
