apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mfg-release
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./.charts/ocp-onboard
      sourceRef:
        kind: GitRepository
        name: git-repo-openshift-gitops
        namespace: flux-system
      reconcileStrategy: Revision
      version: '*'
      interval: 1m
      valuesFiles:
      - /path/to/values.yaml    
#  valuesFrom:
#     - kind: ConfigMap
#       name: mfg-sandbox-values
#       valueKey: values.yaml
  #values:
  #- chartFileRef:
  #    path: to-be-replaced.yaml   
