apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-repo-openshift-charts
  namespace: flux-system
spec:
  interval: 5m0s
  url: "https://github.com/volvo-cars/openshift-charts.git"
  ref:
    branch: main
  secretRef:
    name: git-vcc-auth
