apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../base
configMapGenerator:
  - name: mfg-access-sandbox-values
    files:
      - values.yaml=values-sandbox-net.yaml

patches:
  - target:
      kind: HelmRelease
      name: mfg-access-sandbox-release
  - patch: |-
      - op: add
        path: /spec/valuesFrom
        values:
          - chartFileRef:
              path: values-sandbox-net.yaml
