apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vida-qa-rb
  namespace: vida-qa
subjects:
- kind: Group
  name: cld-vidaadm-sg   
roleRef:
  kind: ClusterRole
  name: admin