apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-test-argoapp 
  namespace: argocd
spec:
  destination:
    namespace: demo-test
    server: https://kubernetes.default.svc
  project: demo-test-appproject
  source:
    path: demo-app
    repoURL: https://github.com/dbacademy/demo-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false