apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-test-rb
  namespace: demo-test
subjects:
- kind: Group
  name: cld-openshift-clusteradmin-sg   
roleRef:
  kind: ClusterRole
  name: admin