apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vivek-test-argoapp 
  namespace: argocd
spec:
  destination:
    namespace: vivek-test
    server: https://kubernetes.default.svc
  project: vivek-test-appproject
  source:
    path: welcome-php
    repoURL: https://github.com/dbacademy/demo-app.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false