apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-repo-openshift-gitops
  namespace: flux-system
spec:
  interval: 5m0s
  url: "https://github.com/dbacademy/openshift-gitops.git"
  ref:
    branch: master
  secretRef:
    name: git-access-auth