apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demoapp10-rb
  namespace: demoapp10
subjects:
- kind: Group
  name: cld-openshift-clusteradmin-sg   
roleRef:
  kind: ClusterRole
  name: admin