apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demoapp-20-rb
  namespace: demoapp-20
subjects:
- kind: Group
  name: cld-openshift-clusteradmin-sg   
roleRef:
  kind: ClusterRole
  name: admin