apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: venkattest-10-rb
  namespace: venkattest-10
subjects:
- kind: Group
  name: cld-openshift-prod-clusteradmin-sg   
roleRef:
  kind: ClusterRole
  name: admin