name: Email Testing

on:
  pull_request:
    types:
      - opened
    branches: [master]
  workflow_dispatch:     

jobs:
  test_connection:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -vk telnet://10.120.98.70:25
  
  email_notification:
    needs: test_connection
    runs-on: ubuntu-latest
    steps:
    - name: Send Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address:  10.120.98.70
        server_port: 25
        subject: Github Actions job for email test
        to: dbiswas@volvocars.com
        from: Deb Biswas
        body: Email test job of ${{github.repository}}
