name: Email Testing

on:
  pull_request:
    types:
      - opened
    branches: [master]
  workflow_dispatch:     

jobs:
  email_notification:
    name: Email Notification for New PR
    runs-on: openshift-selfhosted-runner    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract pull request number
      id: extract_pr_number
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "The pull request number is $PR_NUMBER"
        echo "::set-output name=PR_NUMBER::$PR_NUMBER"      

    - name: Sending Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address:  10.120.98.70
        server_port: 25
        subject: ${{github.event.pull_request.title}} by ${{github.actor}}
        to: dbiswas@volvocars.com
        #to: stabassu@volvocars.com
        ##cc: jon.nordgren@volvocars.com
        from: ocponboarding@volvocars.com
        body: |
          hi
          You have notification for ${{github.event.pull_request.title}} 
          To approve or reject please check https://github.com/dbacademy/openshift-gitops/pull/${{ steps.extract_pr_number.outputs.PR_NUMBER }}
        convert_markdown: true
#  Telnet-check:
#          To approve or reject please check https://github.com/dbacademy/openshift-gitops/pull/${{github.event.pull_request.number}}  
#          name: Telnet test
#          runs-on: openshift-selfhosted-runner
#          steps:
#            -  name: Telnet
#               run: |
#                curl -vk telnet://10.120.98.70:25
