
# Template workflow for the OpenShift GitHub Connector

name: Check Openshift Namespace Exists
on:
  workflow_dispatch:
    inputs:
      ocp_server:
        description: 'Enter OCP API Server URL'
        required: true
      ocp_token:
        description: 'Enter Login Token'
        required: true
      namespace:
        description: 'Enter Namespace name'
        required: true


jobs:
  openshift:
    name: OpenShift login and test
    runs-on: openshift-selfhosted-runner

    steps:
      #- name: Install OpenShift Client
      #  uses: redhat-actions/openshift-tools-installer@v1
      #  with:
      #    oc: 4

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          #openshift_server_url: ${{ github.event.inputs.ocp_server }}
          #openshift_token: ${{ github.event.inputs.ocp_token }}
          # if you login with secret
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Check Namespace Exists
        run: |
          namespacename=$(kubectl get ns ${{ inputs.namespace }} -o json | jq .status.phase -r)
          if [[ $namespacename == "Active" ]]; then 
            echo "namespace ${{ inputs.namespace }} status is $namespacename"
            echo "namespace ${{ inputs.namespace }} already existis into cluster ${{ env.OPENSHIFT_SERVER }}"
            exit 1
          else
            echo "namespace ${{ inputs.namespace }} does not existis into cluster ${{ env.OPENSHIFT_SERVER }}"  
            echo "namespace ${{ inputs.namespace }} creation will cuntinue...."
          fi
      - name: Test
        run: oc get co
